(()=>{'use strict';
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co';
const SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const APP_URL='https://guoer11.github.io/pokemon-lp-tracker/';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const N={great:'超級球',premier:'紀念球',ultra:'高級球',master:'大師球'};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=$('form'),date=$('date'),loc=$('location'),league=$('league'),parts=$('participants'),place=$('placement'),lp=$('lp'),help=$('scoreHelp'),preview=$('preview'),msg=$('msg'),list=$('list'),empty=$('empty'),filter=$('filter');
let events=[],decks=[],matches=[],session=null,editingId=null,expandedId=null,busy=false,deckTarget=null;
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
function gScore(p,r){if(!Number.isInteger(p)||p<17||p>256||!Number.isInteger(r)||r<1||r>p)return 0;let t=[[1,1,20],[2,2,12],[3,4,10],[5,8,8]];if(p>=33)t.push([9,16,6]);if(p>=65)t.push([17,32,4]);if(p>=129)t.push([33,64,3]);for(const[a,b,s]of t)if(r>=a&&r<=b)return s;return 0}
function pScore(p,r){if(!Number.isInteger(p)||p<1||!Number.isInteger(r)||r<1||r>p)return 0;for(const[a,b,s]of [[1,1,150],[2,2,100],[3,4,75],[5,8,50],[9,16,25],[17,32,15],[33,64,10],[65,128,5]])if(r>=a&&r<=b)return s;return 0}
function auto(l,p,r){return l==='great'?gScore(p,r):l==='premier'?pScore(p,r):null}
function scoreMode(){const manual=['ultra','master'].includes(league.value);lp.readOnly=!manual;lp.required=manual;help.textContent=manual?'官方 2026–27 LP 表尚未公布，暫時手動輸入':'依官方規則自動計算';updatePreview()}
function updatePreview(){const a=auto(league.value,Number(parts.value),Number(place.value));if(a===null){const v=Math.max(0,Number(lp.value)||0);preview.innerHTML='目前輸入：<strong>'+v+' LP</strong>（手動）'}else{lp.value=String(a);preview.innerHTML='目前預估：<strong>'+a+' LP</strong>'}}
function readLocal(){try{const x=JSON.parse(localStorage.getItem('pokemon-lp-events')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveLocal(){localStorage.setItem('pokemon-lp-events',JSON.stringify(events))}
function ranked(){return [...events].sort((a,b)=>b.lp-a.lp||a.date.localeCompare(b.date)||String(a.id).localeCompare(String(b.id)))}
function showErr(t){msg.textContent=t;msg.className='msg'}function showOk(t){msg.textContent=t;msg.className='msg ok'}
function setBusy(v,text='同步中…'){busy=v;$('submitBtn').disabled=v;$('uploadLocal').disabled=v;$('syncState').textContent=v?text:(session?'已與 Supabase 雲端同步':'登入 Google 後可在手機與電腦同步');$('syncState').className='sync'+(!v&&session?' ok':'')}
function mapEvent(r){return{id:r.id,date:r.event_date,location:r.location,league:r.league_type,participants:r.participants,placement:r.placement,lp:r.lp,manual:['ultra','master'].includes(r.league_type),createdAt:new Date(r.created_at).getTime(),ownDeckId:r.own_deck_id||null}}
function toEventRow(e){return{user_id:session.user.id,season:'2026-27',event_date:e.date,location:e.location,league_type:e.league,participants:e.participants,placement:e.placement,lp:e.lp,own_deck_id:e.ownDeckId||null}}
function mapDeck(r){return{id:r.id,name:r.name,image:r.image_data||null}}
function mapMatch(r){return{id:r.id,eventId:r.event_id,roundNo:r.round_no,result:r.result,turnOrder:r.turn_order,deckId:r.opponent_deck_id||null,deckName:r.opponent_deck_name||'',notes:r.notes||''}}
function deckById(id){return decks.find(d=>d.id===id)||null}
function deckOptions(selected){return '<option value="">尚未選擇牌組</option>'+decks.map(d=>'<option value="'+d.id+'" '+(d.id===selected?'selected':'')+'>'+esc(d.name)+'</option>').join('')}
function deckVisual(d,small=false){if(!d)return '<div class="deck-thumb deck-fallback">?</div>';if(d.image)return '<img class="deck-thumb" src="'+d.image+'" alt="'+esc(d.name)+'">';return '<div class="deck-thumb deck-fallback">'+esc((d.name||'?').slice(0,1))+'</div>'}
function authUI(){const logged=!!session;$('login').hidden=logged;$('logout').hidden=!logged;$('authState').textContent=logged?'雲端同步模式':'本機模式';$('authEmail').textContent=logged?(session.user.email||'Google 帳號已登入'):'尚未登入，紀錄只存在這台裝置';$('storageText').textContent=logged?'比賽與戰報儲存在 Supabase，手機與電腦登入同一 Google 帳號即可共用。':'目前為本機模式，比賽紀錄只存在這台裝置；戰報需登入後使用。';$('cloudBox').hidden=!logged||readLocal().length===0;if(!busy){$('syncState').textContent=logged?'已與 Supabase 雲端同步':'登入 Google 後可在手機與電腦同步';$('syncState').className='sync'+(logged?' ok':'')}}
async function loadCloud(){if(!session)return;setBusy(true,'讀取雲端資料…');const uid=session.user.id;const [er,dr,mr]=await Promise.all([sb.from('events').select('*').eq('user_id',uid).order('event_date',{ascending:false}).order('created_at',{ascending:false}),sb.from('decks').select('*').eq('user_id',uid).order('name'),sb.from('matches').select('*').eq('user_id',uid).order('round_no')]);if(er.error||dr.error||mr.error){setBusy(false);showErr('雲端讀取失敗：'+(er.error||dr.error||mr.error).message);return}events=(er.data||[]).map(mapEvent);decks=(dr.data||[]).map(mapDeck);matches=(mr.data||[]).map(mapMatch);render();setBusy(false);authUI()}
function render(){const r=ranked(),best=r.slice(0,8),ids=new Set(best.map(x=>x.id));$('total').textContent=best.reduce((s,x)=>s+x.lp,0);$('count').textContent=events.length;$('cutoff').textContent=events.length>=8?best[7].lp:'—';const visible=[...events].filter(x=>filter.value==='all'||x.league===filter.value).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);empty.hidden=visible.length>0;list.innerHTML='';for(const e of visible)list.appendChild(renderEventCard(e,ids.has(e.id)))}
function renderEventCard(e,isBest){const card=document.createElement('article');card.className='event-card'+(isBest?' best':'');const own=deckById(e.ownDeckId),ms=matches.filter(m=>m.eventId===e.id),rec=recordOf(ms);card.innerHTML='<div class="event-main"><div><div class="badges">'+(isBest?'<span class="badge bestbadge">★ BEST 8</span>':'')+'<span class="badge">'+N[e.league]+'</span><span class="date">'+e.date.replaceAll('-','/')+'</span></div><h3 class="loc">'+esc(e.location)+'</h3><div class="meta">參加 '+e.participants+' 人｜第 '+e.placement+' 名'+(own?'｜'+esc(own.name):'')+(ms.length?'｜'+rec.text:'')+'</div><div class="expand-tip">'+(expandedId===e.id?'▲ 收起戰報':'▼ 點此展開戰報')+'</div></div><div class="score"><strong>'+e.lp+'</strong><span>LP</span></div><div class="rowactions"><button class="mini edit" type="button">編輯</button><button class="mini del" type="button">刪除</button></div></div>'+(expandedId===e.id?reportHtml(e):'');
const main=card.querySelector('.event-main');main.addEventListener('click',()=>{expandedId=expandedId===e.id?null:e.id;render()});card.querySelector('.edit').addEventListener('click',ev=>{ev.stopPropagation();startEdit(e)});card.querySelector('.del').addEventListener('click',ev=>{ev.stopPropagation();removeEvent(e)});if(expandedId===e.id)bindReport(card,e);return card}
function recordOf(ms){let w=0,l=0,d=0;for(const m of ms){if(m.result==='W')w++;else if(m.result==='L')l++;else if(m.result==='D')d++}return{w,l,d,text:w+'W '+l+'L'+(d?' '+d+'D':'')}}
function reportHtml(e){if(!session)return '<div class="report"><div class="report-empty">請先使用 Google 登入，戰報才會同步到手機與電腦。</div></div>';const own=deckById(e.ownDeckId),ms=matches.filter(m=>m.eventId===e.id).sort((a,b)=>a.roundNo-b.roundNo),rec=recordOf(ms);return '<div class="report"><div class="report-head"><div><h2>戰報</h2><div class="hint" style="margin:2px 0 0">每輪紀錄會自動同步到雲端</div></div><div class="record"><b class="w">'+rec.w+'W</b><b class="l">'+rec.l+'L</b>'+(rec.d?'<b class="d">'+rec.d+'D</b>':'')+'</div></div><div class="deck-hero">'+deckVisual(own)+'<div class="deck-copy"><small>我的牌組</small><strong>'+(own?esc(own.name):'尚未選擇')+'</strong><div class="deck-controls"><select class="own-deck">'+deckOptions(e.ownDeckId)+'</select><button class="btn small new-own-deck" type="button">＋ 新增牌組</button></div></div></div><div class="rounds">'+(ms.length?ms.map(roundHtml).join(''):'<div class="report-empty">還沒有對局紀錄，按「新增一輪」開始。</div>')+'</div><div class="actions" style="margin-top:12px"><button class="btn primary small add-round" type="button">＋ 新增一輪</button></div></div>'}
function roundHtml(m){const d=deckById(m.deckId);return '<div class="round" data-match="'+m.id+'"><div class="round-no">R'+m.roundNo+'</div><select class="r-result"><option value="N" '+(m.result==='N'?'selected':'')+'>未填</option><option value="W" '+(m.result==='W'?'selected':'')+'>W 勝</option><option value="L" '+(m.result==='L'?'selected':'')+'>L 敗</option><option value="D" '+(m.result==='D'?'selected':'')+'>D 和</option></select><select class="r-turn"><option value="unknown" '+(m.turnOrder==='unknown'?'selected':'')+'>先後攻？</option><option value="first" '+(m.turnOrder==='first'?'selected':'')+'>先攻</option><option value="second" '+(m.turnOrder==='second'?'selected':'')+'>後攻</option></select><div class="round-deck">'+deckVisual(d,true)+'<div style="min-width:0;flex:1"><select class="r-deck">'+deckOptions(m.deckId)+'</select></div></div><div class="round-extra"><input class="r-note" maxlength="120" placeholder="備註（選填）" value="'+esc(m.notes)+'"><button class="btn small new-r-deck" type="button">＋牌組</button><button class="btn small save-round" type="button">儲存</button><button class="btn small danger delete-round" type="button">刪除</button></div></div>'}
function bindReport(card,e){if(!session)return;const ownSel=card.querySelector('.own-deck');ownSel?.addEventListener('change',async()=>{setBusy(true,'更新我的牌組…');const id=ownSel.value||null,{error}=await sb.from('events').update({own_deck_id:id}).eq('id',e.id).eq('user_id',session.user.id);setBusy(false);if(error)return showErr(error.message);e.ownDeckId=id;render()});card.querySelector('.new-own-deck')?.addEventListener('click',()=>openDeckDialog({type:'event',id:e.id}));card.querySelector('.add-round')?.addEventListener('click',()=>addRound(e.id));card.querySelectorAll('.round').forEach(row=>{const id=row.dataset.match,m=matches.find(x=>x.id===id);row.querySelector('.r-deck').addEventListener('change',()=>{const d=deckById(row.querySelector('.r-deck').value);const holder=row.querySelector('.round-deck');const old=holder.querySelector('.deck-thumb');if(old)old.outerHTML=deckVisual(d,true)});row.querySelector('.new-r-deck').addEventListener('click',()=>openDeckDialog({type:'match',id}));row.querySelector('.save-round').addEventListener('click',()=>saveRound(row,m));row.querySelector('.delete-round').addEventListener('click',()=>deleteRound(m))})}
async function addRound(eventId){const ms=matches.filter(m=>m.eventId===eventId),next=ms.length?Math.max(...ms.map(x=>x.roundNo))+1:1;setBusy(true,'新增對局…');const{data,error}=await sb.from('matches').insert({event_id:eventId,user_id:session.user.id,round_no:next,result:'N',turn_order:'unknown'}).select().single();setBusy(false);if(error)return showErr('新增對局失敗：'+error.message);matches.push(mapMatch(data));render()}
async function saveRound(row,m){const result=row.querySelector('.r-result').value,turn=row.querySelector('.r-turn').value,deckId=row.querySelector('.r-deck').value||null,note=row.querySelector('.r-note').value.trim(),d=deckById(deckId);setBusy(true,'儲存戰報…');const{data,error}=await sb.from('matches').update({result,turn_order:turn,opponent_deck_id:deckId,opponent_deck_name:d?.name||null,notes:note||null}).eq('id',m.id).eq('user_id',session.user.id).select().single();setBusy(false);if(error)return showErr('戰報儲存失敗：'+error.message);matches=matches.map(x=>x.id===m.id?mapMatch(data):x);showOk('戰報已儲存。');render()}
async function deleteRound(m){if(!confirm('刪除 R'+m.roundNo+' 這筆對局？'))return;setBusy(true,'刪除對局…');const{error}=await sb.from('matches').delete().eq('id',m.id).eq('user_id',session.user.id);setBusy(false);if(error)return showErr(error.message);matches=matches.filter(x=>x.id!==m.id);render()}
function openDeckDialog(target){deckTarget=target;$('deckName').value='';$('deckImage').value='';$('deckPreview').style.display='none';$('deckMsg').textContent='';$('deckDialog').showModal();setTimeout(()=>$('deckName').focus(),100)}
function closeDeckDialog(){$('deckDialog').close();deckTarget=null}
async function imageToData(file){if(!file)return null;return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const s=160,c=document.createElement('canvas');c.width=c.height=s;const ctx=c.getContext('2d'),scale=Math.max(s/img.width,s/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(s-w)/2,(s-h)/2,w,h);const out=c.toDataURL('image/webp',.82);URL.revokeObjectURL(url);resolve(out)}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('圖片讀取失敗'))};img.src=url})}
async function createDeck(ev){ev.preventDefault();const name=$('deckName').value.trim();if(!name)return $('deckMsg').textContent='請輸入牌組名稱。';$('deckSave').disabled=true;try{const image=await imageToData($('deckImage').files[0]),{data,error}=await sb.from('decks').insert({user_id:session.user.id,name,image_data:image}).select().single();if(error)throw error;const d=mapDeck(data);decks.push(d);decks.sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant'));if(deckTarget?.type==='event'){await sb.from('events').update({own_deck_id:d.id}).eq('id',deckTarget.id).eq('user_id',session.user.id);const e=events.find(x=>x.id===deckTarget.id);if(e)e.ownDeckId=d.id}else if(deckTarget?.type==='match'){await sb.from('matches').update({opponent_deck_id:d.id,opponent_deck_name:d.name}).eq('id',deckTarget.id).eq('user_id',session.user.id);const m=matches.find(x=>x.id===deckTarget.id);if(m){m.deckId=d.id;m.deckName=d.name}}closeDeckDialog();render();showOk('牌組「'+name+'」已加入牌組庫。')}catch(e){$('deckMsg').textContent=e.message?.includes('duplicate')?'這個牌組名稱已經存在。':('新增牌組失敗：'+(e.message||e))}finally{$('deckSave').disabled=false}}
function startEdit(e){editingId=e.id;date.value=e.date;loc.value=e.location;league.value=e.league;parts.value=e.participants;place.value=e.placement;lp.value=e.lp;$('formTitle').textContent='編輯比賽';$('submitBtn').textContent='儲存修改';msg.textContent='';scoreMode();window.scrollTo({top:f.getBoundingClientRect().top+window.scrollY-20,behavior:'smooth'})}
function resetForm(){editingId=null;f.reset();date.value=today();league.value='great';msg.textContent='';msg.className='msg';$('formTitle').textContent='新增比賽';$('submitBtn').textContent='儲存比賽';scoreMode()}
async function removeEvent(e){if(!confirm('刪除這筆比賽？相關戰報也會一起刪除。'))return;if(session){setBusy(true,'刪除雲端資料…');const{error}=await sb.from('events').delete().eq('id',e.id).eq('user_id',session.user.id);setBusy(false);if(error)return showErr('刪除失敗：'+error.message);events=events.filter(x=>x.id!==e.id);matches=matches.filter(x=>x.eventId!==e.id)}else{events=events.filter(x=>x.id!==e.id);saveLocal()}if(expandedId===e.id)expandedId=null;render();resetForm()}
async function submitEvent(ev){ev.preventDefault();const p=Number(parts.value),r=Number(place.value),a=auto(league.value,p,r),v=a===null?Number(lp.value):a;if(!date.value)return showErr('請選擇比賽日期。');if(!loc.value.trim())return showErr('請輸入比賽地點。');if(!Number.isInteger(p)||p<1)return showErr('參加人數要大於 0。');if(!Number.isInteger(r)||r<1||r>p)return showErr('請確認最終名次。');if(league.value==='great'&&(p<17||p>256))return showErr('超級球官方 LP 表適用 17～256 人。');if(!Number.isFinite(v)||v<0)return showErr('請輸入有效 LP。');const old=events.find(x=>x.id===editingId),obj={id:editingId||((crypto.randomUUID&&crypto.randomUUID())||Date.now()+'-'+Math.random()),date:date.value,location:loc.value.trim(),league:league.value,participants:p,placement:r,lp:v,manual:a===null,createdAt:old?.createdAt||Date.now(),ownDeckId:old?.ownDeckId||null};if(session){setBusy(true,editingId?'更新雲端資料…':'儲存到雲端…');if(editingId){const{data,error}=await sb.from('events').update(toEventRow(obj)).eq('id',editingId).eq('user_id',session.user.id).select().single();setBusy(false);if(error)return showErr('儲存失敗：'+error.message);events=events.map(x=>x.id===editingId?mapEvent(data):x)}else{const{data,error}=await sb.from('events').insert(toEventRow(obj)).select().single();setBusy(false);if(error)return showErr('儲存失敗：'+error.message);events.push(mapEvent(data))}}else{if(editingId)events=events.map(x=>x.id===editingId?obj:x);else events.push(obj);saveLocal()}render();resetForm();showOk('已儲存。')}
async function uploadLocal(){if(!session)return;const local=readLocal();if(!local.length)return;if(!confirm('將這台裝置的 '+local.length+' 筆本機紀錄上傳到雲端？\n\n雲端已有相同賽事時不會自動判斷重複。'))return;setBusy(true,'上傳本機資料…');const rows=local.filter(x=>x&&x.date&&x.location&&N[x.league]).map(x=>({user_id:session.user.id,season:'2026-27',event_date:x.date,location:x.location,league_type:x.league,participants:Number(x.participants),placement:Number(x.placement),lp:Number(x.lp)}));const{error}=await sb.from('events').insert(rows);setBusy(false);if(error)return showErr('上傳失敗：'+error.message);localStorage.removeItem('pokemon-lp-events');await loadCloud();showOk('本機紀錄已上傳到雲端。');authUI()}
$('login').addEventListener('click',async()=>{const{error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)showErr('Google 登入失敗：'+error.message)});$('logout').addEventListener('click',async()=>{await sb.auth.signOut();session=null;events=readLocal();decks=[];matches=[];expandedId=null;authUI();render();resetForm()});
f.addEventListener('submit',submitEvent);[league,parts,place,lp].forEach(x=>x.addEventListener('input',()=>x===league?scoreMode():updatePreview()));$('reset').addEventListener('click',resetForm);filter.addEventListener('change',render);$('uploadLocal').addEventListener('click',uploadLocal);$('deckForm').addEventListener('submit',createDeck);$('deckCancel').addEventListener('click',closeDeckDialog);$('deckImage').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=await imageToData(file);$('deckPreview').src=data;$('deckPreview').style.display='block'}catch{}});
$('export').addEventListener('click',()=>{const b=new Blob([JSON.stringify(events,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='pokemon-lp-backup.json';a.click();URL.revokeObjectURL(u)});
$('import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d))throw 0;const incoming=d.filter(x=>x&&x.date&&x.location&&N[x.league]&&Number.isFinite(Number(x.lp))).map(x=>({date:x.date,location:x.location,league:x.league,participants:Number(x.participants),placement:Number(x.placement),lp:Number(x.lp),manual:['ultra','master'].includes(x.league)}));if(session){const rows=incoming.map(x=>({user_id:session.user.id,season:'2026-27',event_date:x.date,location:x.location,league_type:x.league,participants:x.participants,placement:x.placement,lp:x.lp})),{error}=await sb.from('events').insert(rows);if(error)throw error;await loadCloud()}else{events=incoming.map(x=>({...x,id:(crypto.randomUUID&&crypto.randomUUID())||Date.now()+'-'+Math.random(),createdAt:Date.now()}));saveLocal();render()}showOk('備份已匯入。')}catch(err){showErr('備份檔格式不正確'+(err?.message?'：'+err.message:'。'))}e.target.value=''});
(async()=>{date.value=today();scoreMode();const{data}=await sb.auth.getSession();session=data.session;authUI();if(session)await loadCloud();else{events=readLocal();render()}sb.auth.onAuthStateChange(async(_event,newSession)=>{const old=session?.user?.id,now=newSession?.user?.id;session=newSession;authUI();if(old!==now){if(session)await loadCloud();else{events=readLocal();decks=[];matches=[];expandedId=null;render()}}})})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();