(()=>{'use strict';
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co';
const SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,secondaryByMatch=new Map(),historyById=new Map(),pickerRow=null,pickerTimer=null;
const savedMatchIds=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').trim().toLocaleLowerCase('zh-Hant');
const sprite=id=>window.PokemonCatalog?.sprite?window.PokemonCatalog.sprite(id):`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
const specialSecondaryItems=q=>{const all=Array.isArray(window.SecondaryItemCatalog)?window.SecondaryItemCatalog:[],needle=norm(q);return needle?all.filter(x=>norm(`${x.name} ${x.keywords||''}`).includes(needle)):all};
function specialSecondaryHtml(items){return items.map(x=>'<button class="secondary-result secondary-item-result" type="button" data-secondary-item="'+esc(x.key)+'"><img src="'+esc(x.imageUrl)+'" alt="'+esc(x.name)+'"><span><b>'+esc(x.name)+'</b><small>特殊道具圖示</small></span></button>').join('')}
function bindSpecialSecondary(box,items){box.querySelectorAll('[data-secondary-item]').forEach(btn=>btn.addEventListener('click',()=>{if(!pickerRow)return;const item=items.find(x=>x.key===btn.dataset.secondaryItem);if(item){setSecondary(pickerRow,{pokemonId:null,pokemonName:item.name,imageUrl:item.imageUrl});ensureDialog().close()}}))}
function showSecondaryStart(){const d=ensureDialog(),box=d.querySelector('.secondary-results'),items=specialSecondaryItems('');box.innerHTML=specialSecondaryHtml(items)||'<div class="secondary-empty">輸入寶可夢名稱開始搜尋。</div>';bindSpecialSecondary(box,items)}
function ensureDialog(){let d=document.getElementById('secondaryPickerDialog');if(d)return d;d=document.createElement('dialog');d.id='secondaryPickerDialog';d.className='secondary-dialog';d.innerHTML='<div class="secondary-dialog-inner"><div class="secondary-dialog-head"><div><h3>選擇副打手</h3><p>可選第二隻代表寶可夢，也可用錘子或斗篷圖示。</p></div><button class="secondary-close" type="button" aria-label="關閉">×</button></div><input class="secondary-search" type="search" autocomplete="off" placeholder="搜尋：錘子、斗篷、巨金怪…"><div class="secondary-results"><div class="secondary-empty">輸入寶可夢名稱開始搜尋。</div></div><div class="secondary-dialog-actions"><button class="secondary-clear" type="button">清除副打手</button></div></div>';document.body.appendChild(d);d.querySelector('.secondary-close').addEventListener('click',()=>d.close());d.querySelector('.secondary-clear').addEventListener('click',()=>{if(pickerRow){setSecondary(pickerRow,null);d.close()}});const input=d.querySelector('.secondary-search');input.addEventListener('input',()=>{clearTimeout(pickerTimer);pickerTimer=setTimeout(()=>searchSecondary(input.value),140)});d.addEventListener('close',()=>{pickerRow=null;input.value='';d.querySelector('.secondary-results').innerHTML='<div class="secondary-empty">輸入寶可夢名稱開始搜尋。</div>'});return d}
function getSecondary(row){const id=row?.dataset.match;if(!id)return null;const local=row.__secondaryState;if(local!==undefined)return local;return secondaryByMatch.get(id)||null}
function setSecondary(row,p){if(!row)return;const id=row.dataset.match;if(p){const x={pokemonId:Number(p.pokemonId??p.id)||null,pokemonName:p.pokemonName??p.zh??'',imageUrl:p.imageUrl??sprite(p.pokemonId??p.id)};row.__secondaryState=x;if(id)secondaryByMatch.set(id,x)}else{row.__secondaryState=null;if(id)secondaryByMatch.set(id,null)}renderSecondaryButton(row)}
function renderSecondaryButton(row){const btn=row.querySelector('.secondary-picker-btn');if(!btn)return;const s=getSecondary(row);if(s?.pokemonId||s?.imageUrl){const url=s.imageUrl||sprite(s.pokemonId);btn.classList.add('has-secondary');btn.innerHTML='<img src="'+esc(url)+'" alt="'+esc(s.pokemonName||'副打手')+'"><span class="secondary-tag">副</span>';btn.title='副打手：'+(s.pokemonName||'已選擇')+'（點一下更換）'}else{btn.classList.remove('has-secondary');btn.innerHTML='<span class="secondary-plus">＋</span><span class="secondary-tag">副</span>';btn.title='點一下選擇副打手'}}
async function searchSecondary(q){const d=ensureDialog(),box=d.querySelector('.secondary-results');q=String(q??'').trim();if(!q){showSecondaryStart();return}box.innerHTML='<div class="secondary-empty">搜尋中…</div>';const specialItems=specialSecondaryItems(q);let pokemonItems=[];try{pokemonItems=window.PokemonCatalog?await window.PokemonCatalog.search(q,18):[]}catch{}if(!specialItems.length&&!pokemonItems.length){box.innerHTML='<div class="secondary-empty">找不到符合的寶可夢或道具圖示。</div>';return}box.innerHTML=specialSecondaryHtml(specialItems)+pokemonItems.map(p=>'<button class="secondary-result" type="button" data-secondary-id="'+p.id+'"><img src="'+sprite(p.id)+'" alt="'+esc(p.zh)+'"><span><b>'+esc(p.zh)+'</b><small>#'+String(p.dexId||p.id).padStart(4,'0')+' '+esc(p.en||'')+(p.isMega?'｜Mega':'')+'</small></span></button>').join('');bindSpecialSecondary(box,specialItems);box.querySelectorAll('[data-secondary-id]').forEach(btn=>btn.addEventListener('click',async()=>{if(!pickerRow)return;const id=Number(btn.dataset.secondaryId);let p=pokemonItems.find(x=>Number(x.id)===id);if(!p&&window.PokemonCatalog){try{p=(await window.PokemonCatalog.search('#'+id,30)).find(x=>Number(x.id)===id)}catch{}}if(p){setSecondary(pickerRow,{pokemonId:p.id,pokemonName:p.zh,imageUrl:sprite(p.id)});d.close()}}))}
function openSecondaryPicker(row){pickerRow=row;const d=ensureDialog(),input=d.querySelector('.secondary-search');input.value='';showSecondaryStart();if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');setTimeout(()=>input.focus(),50)}
function makeSegment(cls,items,select){const wrap=document.createElement('div');wrap.className=cls;for(const [value,label] of items){const b=document.createElement('button');b.type='button';b.className='seg-btn';b.dataset.value=value;b.textContent=label;b.addEventListener('click',()=>{const next=select.value===value?(select.classList.contains('r-result')?'N':'unknown'):value;select.value=next;select.dispatchEvent(new Event('change',{bubbles:true}));syncSegments(select.closest('.round'))});wrap.appendChild(b)}return wrap}
function syncSegments(row){if(!row)return;const rs=row.querySelector('.r-result'),ts=row.querySelector('.r-turn');row.querySelectorAll('.result-segment .seg-btn').forEach(b=>b.classList.toggle('active',b.dataset.value===rs?.value));row.querySelectorAll('.turn-segment .seg-btn').forEach(b=>b.classList.toggle('active',b.dataset.value===ts?.value))}
function ensurePrimaryThumb(row,opWrap){let holder=opWrap.querySelector('.primary-thumb-wrap');if(holder)return holder;const thumb=opWrap.querySelector('.opp-thumb');if(!thumb)return null;holder=document.createElement('span');holder.className='primary-thumb-wrap';thumb.replaceWith(holder);holder.appendChild(thumb);const tag=document.createElement('span');tag.className='primary-tag';tag.textContent='主';holder.appendChild(tag);return holder}
function rowLooksSaved(row){if(!row)return false;const result=row.querySelector('.r-result')?.value||'N',turn=row.querySelector('.r-turn')?.value||'unknown',name=row.querySelector('.r-opponent')?.value.trim()||'',score=row.querySelector('.r-score')?.value||'',pid=row.querySelector('.r-opponent')?.dataset.pokemonId||'',secondary=getSecondary(row);return result!=='N'||turn!=='unknown'||!!name||!!score||!!pid||!!secondary}
function syncSaveButton(row,forceSaved=false){const btn=row?.querySelector('.save-round');if(!btn)return;const id=String(row.dataset.match||'');const saved=forceSaved||savedMatchIds.has(id)||rowLooksSaved(row);btn.dataset.saveMode=saved?'edit':'save';btn.textContent=saved?'修改':'儲存';btn.classList.remove('saving','saved-flash')}
function flashSaved(matchId){savedMatchIds.add(String(matchId));const row=[...document.querySelectorAll('.round')].find(r=>String(r.dataset.match)===String(matchId));const btn=row?.querySelector('.save-round');if(!btn)return;btn.dataset.saveMode='edit';btn.textContent='已儲存 ✓';btn.classList.remove('saving');btn.classList.add('saved-flash');setTimeout(()=>{const current=[...document.querySelectorAll('.round')].find(r=>String(r.dataset.match)===String(matchId));if(current)syncSaveButton(current,true)},850)}
function decorateRound(row){if(!row||row.dataset.v12==='1')return;const result=row.querySelector('.r-result'),turn=row.querySelector('.r-turn'),opWrap=row.querySelector('.opponent-input-wrap');if(!result||!turn||!opWrap)return;row.dataset.v12='1';const resultSeg=makeSegment('result-segment',[['W','W'],['L','L'],['D','D']],result);const turnSeg=makeSegment('turn-segment',[['first','先'],['second','後']],turn);result.before(resultSeg);turn.before(turnSeg);ensurePrimaryThumb(row,opWrap);const secondaryBtn=document.createElement('button');secondaryBtn.type='button';secondaryBtn.className='secondary-picker-btn';secondaryBtn.setAttribute('aria-label','選擇副打手');const nameInput=opWrap.querySelector('.r-opponent');if(nameInput)opWrap.insertBefore(secondaryBtn,nameInput);else opWrap.appendChild(secondaryBtn);secondaryBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openSecondaryPicker(row)});result.addEventListener('change',()=>syncSegments(row));turn.addEventListener('change',()=>syncSegments(row));row.querySelector('.r-score')?.addEventListener('change',()=>setTimeout(()=>syncSegments(row),0));syncSegments(row);renderSecondaryButton(row);syncSaveButton(row)}
function decorateAll(){document.querySelectorAll('.round').forEach(decorateRound)}
async function loadSecondary(){if(!session){secondaryByMatch.clear();historyById.clear();decorateAll();return}const uid=session.user.id;const [mr,hr]=await Promise.all([db.from('matches').select('id,secondary_pokemon_id,secondary_pokemon_name,secondary_image_url').eq('user_id',uid),db.from('opponent_deck_history').select('id,secondary_pokemon_id,secondary_pokemon_name,secondary_image_url').eq('user_id',uid)]);if(!mr.error){secondaryByMatch.clear();for(const r of mr.data||[])secondaryByMatch.set(String(r.id),r.secondary_pokemon_id||r.secondary_image_url?{pokemonId:r.secondary_pokemon_id||null,pokemonName:r.secondary_pokemon_name||'',imageUrl:r.secondary_image_url||''}:null)}if(!hr.error){historyById.clear();for(const r of hr.data||[])historyById.set(String(r.id),r)}decorateAll();document.querySelectorAll('.round').forEach(r=>{delete r.__secondaryState;renderSecondaryButton(r);syncSaveButton(r)})}
async function saveSecondarySnapshot(matchId,snap,deckName){if(!session||!matchId)return;const payload={secondary_pokemon_id:snap?.pokemonId||null,secondary_pokemon_name:snap?.pokemonName||null,secondary_image_url:snap?.imageUrl||null};const{error}=await db.from('matches').update(payload).eq('id',matchId).eq('user_id',session.user.id);if(!error)secondaryByMatch.set(String(matchId),snap||null);if(deckName){const normalized=norm(deckName);await db.from('opponent_deck_history').update(payload).eq('user_id',session.user.id).eq('normalized_name',normalized)}}
function snapshotRow(row){const s=getSecondary(row),name=row.querySelector('.r-opponent')?.value.trim()||'';return{matchId:row.dataset.match,secondary:s?{pokemonId:s.pokemonId||null,pokemonName:s.pokemonName||'',imageUrl:s.imageUrl||''}:null,deckName:name}}
function installJwtRecovery(){const key='pokemon-lp-jwt-future-retry',msg=document.getElementById('msg');if(!msg)return;let healing=false;async function check(){const text=(msg.textContent||'').toLowerCase();if(!text.includes('jwt issued at future')||healing)return;healing=true;const n=Number(sessionStorage.getItem(key)||0);const sync=document.getElementById('syncState');if(sync)sync.textContent='登入憑證時間校正中，正在自動重試…';if(n===0){sessionStorage.setItem(key,'1');setTimeout(()=>location.reload(),2600);return}if(n===1){sessionStorage.setItem(key,'2');setTimeout(async()=>{try{await db.auth.refreshSession()}catch{}setTimeout(()=>location.reload(),1200)},3600);return}if(sync)sync.textContent='登入憑證暫時不同步，請稍後重新開啟或重新登入 Google';healing=false}const mo=new MutationObserver(check);mo.observe(msg,{childList:true,subtree:true,characterData:true});check();setTimeout(()=>{if(!(msg.textContent||'').toLowerCase().includes('jwt issued at future'))sessionStorage.removeItem(key)},20000)}
const observer=new MutationObserver(()=>decorateAll());observer.observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('click',e=>{const save=e.target.closest?.('.save-round');if(save){const row=save.closest('.round');if(row){const snap=snapshotRow(row),id=snap.matchId;save.textContent='儲存中…';save.classList.add('saving');setTimeout(()=>saveSecondarySnapshot(id,snap.secondary,snap.deckName),350);setTimeout(()=>{const err=(document.getElementById('msg')?.textContent||'').toLowerCase();if(err.includes('戰報儲存失敗')||err.includes('jwt issued at future')){const current=[...document.querySelectorAll('.round')].find(r=>String(r.dataset.match)===String(id));if(current)syncSaveButton(current);return}flashSaved(id)},700)}return}},true);
document.addEventListener('mousedown',e=>{const pick=e.target.closest?.('[data-history-id]');if(!pick)return;const row=pick.closest('.round');const h=historyById.get(String(pick.dataset.historyId));if(row&&h){const s=h.secondary_pokemon_id||h.secondary_image_url?{pokemonId:h.secondary_pokemon_id||null,pokemonName:h.secondary_pokemon_name||'',imageUrl:h.secondary_image_url||''}:null;setSecondary(row,s)}},true);
(async()=>{ensureDialog();installJwtRecovery();const{data}=await db.auth.getSession();session=data.session;await loadSecondary();decorateAll();db.auth.onAuthStateChange(async(_event,newSession)=>{const old=session?.user?.id,now=newSession?.user?.id;session=newSession;if(old!==now)await loadSecondary()})})();
})();
