(()=>{'use strict';
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co';
const SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,gamesByMatch=new Map();
function stateFor(matchId){const saved=gamesByMatch.get(String(matchId))||[];const out={};for(let n=1;n<=3;n++){const g=saved.find(x=>Number(x.game_no)===n);out[n]={gameNo:n,result:g?.result||'N',turnOrder:g?.turn_order||'unknown'}}return out}
function cloneState(s){const out={};for(let n=1;n<=3;n++)out[n]={...s[n]};return out}
async function loadGames(){if(!session){gamesByMatch.clear();decorateAll(true);return}const{data,error}=await db.from('match_games').select('match_id,game_no,result,turn_order').eq('user_id',session.user.id).order('game_no');if(!error){gamesByMatch.clear();for(const g of data||[]){const id=String(g.match_id),arr=gamesByMatch.get(id)||[];arr.push(g);gamesByMatch.set(id,arr)}decorateAll(true)}}
function gameButtons(type,game){const items=type==='result'?[['W','W'],['L','L'],['D','D']]:[['first','先'],['second','後']];const current=type==='result'?game.result:game.turnOrder;return `<div class="bo3-${type}-buttons">${items.map(([v,t])=>`<button type="button" class="bo3-choice ${current===v?'active':''}" data-kind="${type}" data-value="${v}">${t}</button>`).join('')}</div>`}
function gameRow(game){return `<div class="bo3-game" data-game="${game.gameNo}"><div class="bo3-game-label">G${game.gameNo}</div>${gameButtons('result',game)}${gameButtons('turn',game)}</div>`}
function ensureScoreOption(sel,value){if(!sel||!value)return;if(![...sel.options].some(o=>o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=value;sel.appendChild(o)}sel.value=value}
function aggregate(row){const s=row.__bo3State;if(!s)return;let w=0,l=0,d=0,filled=0;for(let n=1;n<=3;n++){const r=s[n].result;if(r==='W'){w++;filled++}else if(r==='L'){l++;filled++}else if(r==='D'){d++;filled++}}let overall='N';if(filled){if(w>l)overall='W';else if(l>w)overall='L';else overall='D'}const rs=row.querySelector('.r-result'),ts=row.querySelector('.r-turn'),score=row.querySelector('.r-score');if(rs&&rs.value!==overall){rs.value=overall;rs.dispatchEvent(new Event('change',{bubbles:true}))}if(ts){const firstTurn=[1,2,3].map(n=>s[n].turnOrder).find(x=>x&&x!=='unknown')||'unknown';if(ts.value!==firstTurn){ts.value=firstTurn;ts.dispatchEvent(new Event('change',{bubbles:true}))}}const scoreText=filled?`${w}-${l}`:'';if(score){if(scoreText)ensureScoreOption(score,scoreText);else score.value=''}const summary=row.querySelector('.bo3-overall');if(summary){const html=filled?`<strong>${w}-${l}</strong><span>${d?`｜${d} 和局｜`:'｜'}逐局記錄</span>`:'<strong>BO3</strong><span>逐局記錄</span>';if(summary.dataset.summaryKey!==html){summary.dataset.summaryKey=html;summary.innerHTML=html}}}
function renderState(row){if(!row.__bo3State)row.__bo3State=cloneState(stateFor(row.dataset.match));for(let n=1;n<=3;n++){const game=row.querySelector(`.bo3-game[data-game="${n}"]`),s=row.__bo3State[n];if(!game)continue;game.querySelectorAll('[data-kind="result"]').forEach(b=>b.classList.toggle('active',b.dataset.value===s.result));game.querySelectorAll('[data-kind="turn"]').forEach(b=>b.classList.toggle('active',b.dataset.value===s.turnOrder))}aggregate(row)}
function decorateRow(row,force=false){if(!row||!row.classList.contains('bo3'))return;if(force)delete row.__bo3State;if(row.dataset.bo3v13==='1'&&!force)return;row.dataset.bo3v13='1';if(!row.querySelector('.bo3-overall')){const overall=document.createElement('div');overall.className='bo3-overall';const badge=row.firstElementChild;if(badge?.nextSibling)row.insertBefore(overall,badge.nextSibling);else row.appendChild(overall)}if(!row.querySelector('.bo3-games')){const panel=document.createElement('div');panel.className='bo3-games';panel.innerHTML=[1,2,3].map(n=>gameRow({gameNo:n,result:'N',turnOrder:'unknown'})).join('');const opponent=row.querySelector('.opponent-search');if(opponent)row.insertBefore(panel,opponent);else row.appendChild(panel);panel.addEventListener('click',e=>{const btn=e.target.closest('.bo3-choice');if(!btn)return;const game=btn.closest('.bo3-game'),n=Number(game.dataset.game),kind=btn.dataset.kind,value=btn.dataset.value;if(!row.__bo3State)row.__bo3State=cloneState(stateFor(row.dataset.match));const s=row.__bo3State[n];if(kind==='result')s.result=s.result===value?'N':value;else s.turnOrder=s.turnOrder===value?'unknown':value;renderState(row)})}renderState(row)}
function decorateAll(force=false){document.querySelectorAll('.round.bo3').forEach(r=>decorateRow(r,force))}
function snapshot(row){if(!row.__bo3State)row.__bo3State=cloneState(stateFor(row.dataset.match));return{matchId:String(row.dataset.match),games:[1,2,3].map(n=>({gameNo:n,result:row.__bo3State[n].result,turnOrder:row.__bo3State[n].turnOrder}))}}
function cacheSnapshot(snap){if(!snap?.matchId)return;gamesByMatch.set(String(snap.matchId),snap.games.map(g=>({match_id:String(snap.matchId),game_no:g.gameNo,result:g.result,turn_order:g.turnOrder})))}
async function saveSnapshot(snap){if(!session||!snap?.matchId)return;const rows=snap.games.map(g=>({match_id:snap.matchId,user_id:session.user.id,game_no:g.gameNo,result:g.result,turn_order:g.turnOrder}));const{data,error}=await db.from('match_games').upsert(rows,{onConflict:'match_id,game_no'}).select('match_id,game_no,result,turn_order');if(!error){gamesByMatch.set(String(snap.matchId),data||rows)}else{console.error('BO3 games save failed',error);const sync=document.getElementById('syncState');if(sync)sync.textContent='BO3 逐局資料儲存失敗，請再試一次'}}
const observer=new MutationObserver(muts=>{for(const m of muts){for(const n of m.addedNodes){if(n.nodeType!==1)continue;if(n.matches?.('.round.bo3'))decorateRow(n,false);n.querySelectorAll?.('.round.bo3').forEach(r=>decorateRow(r,false))}}});
observer.observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('click',e=>{const save=e.target.closest?.('.save-round');if(!save)return;const row=save.closest('.round.bo3');if(!row)return;const snap=snapshot(row);aggregate(row);cacheSnapshot(snap);void saveSnapshot(snap)},true);
(async()=>{const{data}=await db.auth.getSession();session=data.session;await loadGames();decorateAll();db.auth.onAuthStateChange(async(_e,s)=>{const old=session?.user?.id,now=s?.user?.id;session=s;if(old!==now)await loadGames()})})();
})();