(()=>{'use strict';
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co';
const SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,history=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').trim().toLocaleLowerCase('zh-Hant');
function sortHistory(){history.sort((a,b)=>new Date(b.last_used_at)-new Date(a.last_used_at)||b.use_count-a.use_count||a.name.localeCompare(b.name,'zh-Hant'))}
async function loadHistory(){if(!session){history=[];return}const{data,error}=await db.from('opponent_deck_history').select('*').eq('user_id',session.user.id).order('last_used_at',{ascending:false}).limit(200);if(!error){history=data||[];sortHistory()}}
function thumbHtml(h){if(h.image_url)return '<img src="'+esc(h.image_url)+'" alt="'+esc(h.name)+'">';if(h.pokemon_id&&window.PokemonCatalog)return '<img src="'+window.PokemonCatalog.sprite(h.pokemon_id)+'" alt="'+esc(h.name)+'">';return '<div class="opp-history-fallback">★</div>'}
function setThumb(input,url,name){const wrap=input.closest('.opponent-input-wrap'),old=wrap?.querySelector('.opp-thumb');if(!old)return;if(url)old.outerHTML='<img class="opp-thumb" src="'+esc(url)+'" alt="'+esc(name||'')+'">';else old.outerHTML='<div class="opp-thumb opp-fallback">?</div>'}
function chooseHistory(input,h){input.value=h.name;input.dataset.pokemonId=h.pokemon_id||'';input.dataset.pokemonName=h.pokemon_name||'';input.dataset.imageUrl=h.image_url||'';setThumb(input,h.image_url||'',h.name);const box=input.closest('.opponent-search')?.querySelector('.opponent-results');if(box)box.hidden=true}
function choosePokemon(input,p){const url=window.PokemonCatalog.sprite(p.id),typed=input.value.trim(),keepCustom=typed&&norm(typed).includes(norm(p.zh));input.value=keepCustom?typed:p.zh;input.dataset.pokemonId=String(p.id);input.dataset.pokemonName=p.zh;input.dataset.imageUrl=url;setThumb(input,url,input.value);const box=input.closest('.opponent-search')?.querySelector('.opponent-results');if(box)box.hidden=true}
function dexLabel(p){return '#'+String(p.dexId||p.id).padStart(4,'0')}
async function showSuggestions(input){const box=input.closest('.opponent-search')?.querySelector('.opponent-results');if(!box)return;const q=input.value.trim(),nq=norm(q);const saved=history.filter(h=>!nq||norm(h.name).includes(nq)||norm(h.pokemon_name||'').includes(nq)).slice(0,10);let api=[];if(q&&window.PokemonCatalog){try{api=await window.PokemonCatalog.search(q,12)}catch{api=[]}}const savedPokemonIds=new Set(saved.map(h=>Number(h.pokemon_id)||0));api=api.filter(p=>!savedPokemonIds.has(Number(p.id))).slice(0,10);let html='';if(saved.length){html+='<div class="opp-section-title">最近／已用過的對手牌組</div>'+saved.map(h=>'<button class="opp-result history-result" type="button" data-history-id="'+h.id+'">'+thumbHtml(h)+'<span><b>'+esc(h.name)+'<i class="history-badge">已記錄</i></b><small>'+(h.pokemon_name?esc(h.pokemon_name)+'｜':'')+'使用 '+h.use_count+' 次</small></span></button>').join('')}if(api.length){html+='<div class="opp-section-title">寶可夢搜尋（選縮圖，名稱仍可再修改）</div>'+api.map(p=>'<button class="opp-result api-result" type="button" data-pokemon-id="'+p.id+'"><img src="'+window.PokemonCatalog.sprite(p.id)+'" alt="'+esc(p.zh)+'"><span><b>'+esc(p.zh)+'</b><small>'+dexLabel(p)+' '+esc(p.en||'')+(p.isMega?'｜Mega':'')+'</small></span></button>').join('')}if(!html){html='<div class="pokemon-empty">'+(q?'找不到符合項目，可直接輸入牌組名稱後儲存。':'尚無對手牌組紀錄，第一次輸入並儲存後就會記住。')+'</div>'}box.innerHTML=html;box.hidden=false;box.querySelectorAll('[data-history-id]').forEach(btn=>btn.addEventListener('mousedown',e=>{e.preventDefault();const h=history.find(x=>x.id===btn.dataset.historyId);if(h)chooseHistory(input,h)}));box.querySelectorAll('[data-pokemon-id]').forEach(btn=>btn.addEventListener('mousedown',async e=>{e.preventDefault();try{const p=(await window.PokemonCatalog.search('#'+btn.dataset.pokemonId,20)).find(x=>String(x.id)===String(btn.dataset.pokemonId));if(p)choosePokemon(input,p)}catch{}}))}
async function rememberOpponent(snap){if(!session||!snap.name)return;const normalized=norm(snap.name);if(!normalized)return;let existing=history.find(h=>h.normalized_name===normalized);const now=new Date().toISOString();if(existing){const payload={name:snap.name,pokemon_id:snap.pokemonId||existing.pokemon_id||null,pokemon_name:snap.pokemonName||existing.pokemon_name||null,image_url:snap.imageUrl||existing.image_url||null,use_count:(existing.use_count||1)+1,last_used_at:now};const{data,error}=await db.from('opponent_deck_history').update(payload).eq('id',existing.id).eq('user_id',session.user.id).select().single();if(!error&&data){history=history.map(h=>h.id===data.id?data:h);sortHistory()}return}const payload={user_id:session.user.id,name:snap.name,normalized_name:normalized,pokemon_id:snap.pokemonId||null,pokemon_name:snap.pokemonName||null,image_url:snap.imageUrl||null,use_count:1,last_used_at:now};const{data,error}=await db.from('opponent_deck_history').insert(payload).select().single();if(!error&&data){history.push(data);sortHistory()}else if(error?.code==='23505'){await loadHistory()}}
function snapFromRow(row){const input=row?.querySelector('.r-opponent');if(!input)return null;return{name:input.value.trim(),pokemonId:Number(input.dataset.pokemonId)||null,pokemonName:input.dataset.pokemonName||null,imageUrl:input.dataset.imageUrl||null}}
document.addEventListener('input',e=>{const input=e.target.closest?.('.r-opponent');if(!input)return;e.stopImmediatePropagation();clearTimeout(input.__historyTimer);input.__historyTimer=setTimeout(()=>showSuggestions(input),160)},true);
document.addEventListener('focus',e=>{const input=e.target.closest?.('.r-opponent');if(!input)return;clearTimeout(input.__historyTimer);input.__historyTimer=setTimeout(()=>showSuggestions(input),30)},true);
document.addEventListener('blur',e=>{const input=e.target.closest?.('.r-opponent');if(!input)return;e.stopImmediatePropagation();setTimeout(()=>{const box=input.closest('.opponent-search')?.querySelector('.opponent-results');if(box)box.hidden=true},220)},true);
document.addEventListener('click',e=>{const btn=e.target.closest?.('.save-round');if(!btn)return;const snap=snapFromRow(btn.closest('.round'));if(snap?.name)setTimeout(()=>rememberOpponent(snap),300)});
function compactLabels(root=document){root.querySelectorAll?.('.r-result').forEach(sel=>{const map={N:'—',W:'W',L:'L',D:'D'};[...sel.options].forEach(o=>{if(map[o.value]!==undefined)o.textContent=map[o.value]})});root.querySelectorAll?.('.r-turn').forEach(sel=>{const map={unknown:'—',first:'先',second:'後'};[...sel.options].forEach(o=>{if(map[o.value]!==undefined)o.textContent=map[o.value]})})}
const observer=new MutationObserver(muts=>{for(const m of muts)for(const n of m.addedNodes)if(n.nodeType===1)compactLabels(n)});observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>compactLabels());else compactLabels();
(async()=>{const{data}=await db.auth.getSession();session=data.session;await loadHistory();db.auth.onAuthStateChange(async(_event,newSession)=>{const old=session?.user?.id,now=newSession?.user?.id;session=newSession;if(old!==now)await loadHistory()})})();
})();