(()=>{'use strict';
const CATALOG_URL='https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_species_names.csv';
const SPRITE=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
const CACHE_KEY='pokemon-catalog-zh-hant-v1';
let catalog=null,loading=null,selected=null;
const $=id=>document.getElementById(id);
function unquote(s){s=String(s??'').trim();if(s.startsWith('"')&&s.endsWith('"'))return s.slice(1,-1).replace(/""/g,'"');return s}
function parseCatalog(text){const map=new Map();for(const line of text.split(/\r?\n/).slice(1)){if(!line)continue;const m=line.match(/^(\d+),(\d+),("(?:[^"]|"")*"|[^,]*),/);if(!m)continue;const id=Number(m[1]),lang=Number(m[2]);if(id<1||id>1025||(lang!==4&&lang!==9))continue;const name=unquote(m[3]);const item=map.get(id)||{id,zh:'',en:''};if(lang===4)item.zh=name;else item.en=name;map.set(id,item)}return [...map.values()].filter(x=>x.zh).sort((a,b)=>a.id-b.id)}
async function loadCatalog(){if(catalog)return catalog;if(loading)return loading;loading=(async()=>{try{const cached=localStorage.getItem(CACHE_KEY);if(cached){const data=JSON.parse(cached);if(Array.isArray(data)&&data.length>900){catalog=data;return catalog}}}catch{}const res=await fetch(CATALOG_URL,{cache:'force-cache'});if(!res.ok)throw new Error('寶可夢資料載入失敗');const text=await res.text();catalog=parseCatalog(text);try{localStorage.setItem(CACHE_KEY,JSON.stringify(catalog))}catch{}return catalog})();try{return await loading}finally{loading=null}}
function resultHtml(p){return `<button class="pokemon-result" type="button" data-id="${p.id}"><img src="${SPRITE(p.id)}" alt="${p.zh}" loading="lazy"><span><b>#${String(p.id).padStart(4,'0')} ${p.zh}</b><small>${p.en||''}</small></span></button>`}
function renderResults(items){const box=$('pokemonResults');if(!box)return;box.innerHTML=items.length?items.map(resultHtml).join(''):'<div class="pokemon-empty">找不到符合的寶可夢</div>';box.hidden=false;box.querySelectorAll('.pokemon-result').forEach(btn=>btn.addEventListener('click',()=>choosePokemon(Number(btn.dataset.id))))}
async function search(){const input=$('pokemonSearch'),status=$('pokemonStatus');if(!input)return;const q=input.value.trim().toLowerCase();if(!q){$('pokemonResults').hidden=true;return}status.textContent='搜尋中…';try{const data=await loadCatalog();const n=Number(q.replace(/^#/,''));const items=data.filter(p=>Number.isFinite(n)&&n>0?p.id===n:p.zh.includes(q)||p.en.toLowerCase().includes(q)).slice(0,12);renderResults(items);status.textContent=`已載入 ${data.length} 隻寶可夢資料`}catch(e){status.textContent='寶可夢資料載入失敗，仍可改用下方自行上傳圖片。'}}
async function choosePokemon(id){const data=await loadCatalog(),p=data.find(x=>x.id===id);if(!p)return;selected=p;const status=$('pokemonStatus'),chosen=$('pokemonChosen'),preview=$('deckPreview'),fileInput=$('deckImage');status.textContent='正在套用縮圖…';chosen.hidden=false;chosen.innerHTML=`<img src="${SPRITE(p.id)}" alt="${p.zh}"><div><b>#${String(p.id).padStart(4,'0')} ${p.zh}</b><small>${p.en||''}</small></div><button id="pokemonClear" type="button">清除</button>`;$('pokemonResults').hidden=true;$('pokemonSearch').value=p.zh;try{const res=await fetch(SPRITE(p.id));if(!res.ok)throw new Error();const blob=await res.blob();const file=new File([blob],`pokemon-${p.id}.png`,{type:blob.type||'image/png'});const dt=new DataTransfer();dt.items.add(file);fileInput.files=dt.files;fileInput.dispatchEvent(new Event('change',{bubbles:true}));status.textContent='已選擇 '+p.zh;}catch{preview.src=SPRITE(p.id);preview.style.display='block';status.textContent='縮圖無法寫入檔案欄位，可改用下方自行上傳。'}setTimeout(()=>{$('pokemonClear')?.addEventListener('click',clearPokemon)},0)}
function clearPokemon(){selected=null;$('pokemonSearch').value='';$('pokemonResults').hidden=true;$('pokemonChosen').hidden=true;$('pokemonChosen').innerHTML='';$('pokemonStatus').textContent='輸入繁中名稱、英文名稱或圖鑑編號';$('deckImage').value='';$('deckPreview').style.display='none';$('deckPreview').removeAttribute('src')}
function init(){const input=$('pokemonSearch'),dialog=$('deckDialog');if(!input||!dialog)return;let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(search,180)});input.addEventListener('focus',()=>{if(input.value.trim())search();else loadCatalog().then(data=>$('pokemonStatus').textContent=`已載入 ${data.length} 隻寶可夢資料`).catch(()=>{})});dialog.addEventListener('close',clearPokemon)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();