(()=>{'use strict';
if(window.__pokemonAppPagesV57)return;window.__pokemonAppPagesV57=true;
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co',SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const LEAGUE={all:'全部',great:'超級球',premier:'紀念球',ultra:'高級球',master:'大師球',world:'世界賽'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').toLocaleLowerCase('zh-Hant').replace(/\s+/g,' ').trim();
const ICONS={home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5"/><path d="M9.5 21v-6h5v6"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>',add:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',analysis:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',user:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a4.2 4.2 0 1 0 0-8.4 4.2 4.2 0 0 0 0 8.4Zm0 2c-4.7 0-8 2.4-8 5.1 0 .7.6 1.3 1.3 1.3h13.4c.7 0 1.3-.6 1.3-1.3C20 16.4 16.7 14 12 14Z"/></svg>'};
let db=null,searchRows=[],activeLeague='all',searchTimer=null,loadedUser='';
function getDb(){if(!db&&window.supabase)db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return db}
function stampVersion(){const v=document.querySelector('.app-version-v14');if(v&&v.textContent!=='V5.7'){v.textContent='V5.7';v.title='目前版本 V5.7'}}
function navMarkup(cls){return '<nav class="'+cls+'" aria-label="主要導覽">'+navBtn('home','首頁')+navBtn('search','搜尋')+navBtn('add','新增',true)+navBtn('analysis','分析')+navBtn('account','我的')+'</nav>'}
function navBtn(key,label,add=false){return '<button type="button" class="v57-nav-btn '+(key==='home'?'is-active ':'')+(add?'v57-add':'')+'" data-v57-nav="'+key+'">'+(add?'<span class="v57-add-circle">'+ICONS[key]+'</span>':ICONS[key])+'<span>'+label+'</span></button>'}
function setActive(key){document.querySelectorAll('[data-v57-nav]').forEach(b=>b.classList.toggle('is-active',b.dataset.v57Nav===key))}
function ensurePages(){const app=document.querySelector('.app'),summary=document.querySelector('.summary'),list=document.getElementById('list'),homePanel=list?.closest('section.panel'),bottom=document.querySelector('section.panel.bottom');if(!app||!summary||!homePanel)return;
  homePanel.classList.add('v57-home-panel');
  const listhead=homePanel.querySelector('.listhead');if(listhead&&!listhead.querySelector('.v57-home-count')){const count=document.createElement('span');count.className='v57-home-count';count.textContent=(document.getElementById('count')?.textContent||'0')+' 場';listhead.querySelector('div')?.appendChild(count);const c=document.getElementById('count');if(c)new MutationObserver(()=>count.textContent=(c.textContent||'0')+' 場').observe(c,{childList:true,characterData:true,subtree:true})}
  const filter=document.getElementById('filter');if(filter&&filter.value!=='all'){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}))}
  if(!document.querySelector('.v57-desktop-nav'))document.querySelector('header')?.insertAdjacentHTML('afterend',navMarkup('v57-desktop-nav'));
  if(!document.querySelector('.v57-mobile-nav'))document.body.insertAdjacentHTML('beforeend',navMarkup('v57-mobile-nav'));
  if(!document.querySelector('.v57-page-search')){const search=document.createElement('section');search.className='v57-page v57-page-search v57-page-shell';search.innerHTML='<div class="v57-page-head"><div><h2>搜尋比賽紀錄</h2><p>搜尋地點、自己的牌組、對手牌組或寶可夢；賽事篩選也集中在這裡。</p></div></div><div class="v57-search-help">名次標示依最終名次顯示冠軍／亞軍／TOP 4／TOP 8／TOP 16。LP 總分仍取可計分賽事最高 8 場。</div><div class="v57-search-input-wrap"><input id="searchInputV57" class="v57-search-input" type="search" autocomplete="off" placeholder="搜尋比賽、地點、牌組、對手牌組…"><span class="v57-search-icon">'+ICONS.search+'</span></div><div class="v57-search-chips">'+Object.entries(LEAGUE).map(([k,v])=>'<button type="button" class="v57-chip '+(k==='all'?'is-active':'')+'" data-v57-league="'+k+'">'+v+'</button>').join('')+'</div><div id="searchStatusV57" class="v57-search-status"></div><div id="searchResultsV57" class="v57-search-results"></div>';app.appendChild(search);bindSearch(search)}
  if(!document.querySelector('.v57-page-analysis')){const p=document.createElement('section');p.className='v57-page v57-page-analysis v57-page-shell';p.innerHTML='<div class="v57-page-head"><div><h2>分析</h2><p>這裡會作為之後的賽季與牌組分析頁。</p></div></div><div class="v57-analysis-card"><div class="v57-analysis-icon">'+ICONS.analysis+'</div><h3>分析功能規劃中</h3><p>預計加入年度戰績、自己的牌組使用率與勝率、對手牌組分布，以及勝率／敗率等統計。</p><div class="v57-plan-tags"><span>年度戰績</span><span>牌組使用率</span><span>勝敗率</span><span>對手環境</span></div></div>';app.appendChild(p)}
  if(!document.querySelector('.v57-page-account')){const p=document.createElement('section');p.className='v57-page v57-page-account v57-page-shell';p.innerHTML='<div class="v57-page-head"><div><h2>我的</h2><p>帳號、同步狀態、資料備份與使用說明集中在這裡。</p></div></div><div class="v57-account-summary"><div class="v57-account-avatar">'+ICONS.user+'</div><div class="v57-account-copy"><div class="v57-account-state"></div><div class="v57-account-email"></div><div class="v57-account-sync"></div></div><div class="v57-account-actions"><button type="button" class="btn primary v57-login">使用 Google 登入</button><button type="button" class="btn v57-logout">登出</button></div></div>';if(bottom)p.appendChild(bottom);app.appendChild(p);bindAccount(p)}
  document.body.classList.add('v57-ready');if(!document.body.dataset.v57Page)document.body.dataset.v57Page='home';bindNav();refreshAccount();stampVersion();setTimeout(stampVersion,700)}
function bindNav(){if(document.body.dataset.v57NavBound==='1')return;document.body.dataset.v57NavBound='1';document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-v57-nav]');if(!b)return;const k=b.dataset.v57Nav;if(k==='add'){document.querySelector('.quick-add-v14')?.click();return}await switchPage(k)})}
async function switchPage(key){if(!['home','search','analysis','account'].includes(key))key='home';document.body.dataset.v57Page=key;setActive(key);if(key==='home'){const f=document.getElementById('filter');if(f&&f.value!=='all'){f.value='all';f.dispatchEvent(new Event('change',{bubbles:true}))}window.scrollTo({top:0,behavior:'smooth'});return}window.scrollTo({top:0,behavior:'auto'});if(key==='search'){activeLeague='all';document.querySelectorAll('[data-v57-league]').forEach(x=>x.classList.toggle('is-active',x.dataset.v57League==='all'));const i=document.getElementById('searchInputV57');if(i)i.value='';await loadSearch();setTimeout(()=>i?.focus(),80)}if(key==='account')refreshAccount()}
function bindSearch(root){const input=root.querySelector('#searchInputV57');input.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderSearch,90)});root.querySelectorAll('[data-v57-league]').forEach(btn=>btn.addEventListener('click',()=>{activeLeague=btn.dataset.v57League;root.querySelectorAll('[data-v57-league]').forEach(x=>x.classList.toggle('is-active',x===btn));renderSearch()}));root.querySelector('#searchResultsV57').addEventListener('click',e=>{const b=e.target.closest?.('[data-v57-event]');if(!b)return;const r=searchRows.find(x=>String(x.id)===String(b.dataset.v57Event));if(r)jumpToRecord(r)})}
async function loadSearch(){const status=document.getElementById('searchStatusV57'),client=getDb();if(status)status.textContent='讀取比賽紀錄…';if(!client){searchRows=[];if(status)status.textContent='搜尋功能暫時無法載入。';return}const{data:{session}}=await client.auth.getSession();if(!session){let local=[];try{local=JSON.parse(localStorage.getItem('pokemon-lp-events')||'[]')}catch{}searchRows=(Array.isArray(local)?local:[]).map((e,i)=>({id:e.id||'local-'+i,date:e.date||'',location:e.location||'',league:e.league||'',format:e.matchFormat||'',participants:+e.participants||0,placement:+e.placement||0,lp:+e.lp||0,ownDeck:'',ownPokemon:'',opponents:[],opponentPokemon:[]}));loadedUser='local';renderSearch();return}const uid=session.user.id;if(loadedUser===uid&&searchRows.length){renderSearch();return}const[er,dr,mr]=await Promise.all([client.from('events').select('id,event_date,location,league_type,match_format,participants,placement,lp,own_deck_id').eq('user_id',uid).order('event_date',{ascending:false}),client.from('decks').select('id,name,primary_pokemon_name,secondary_pokemon_name').eq('user_id',uid),client.from('matches').select('event_id,opponent_deck_name,opponent_pokemon_name').eq('user_id',uid)]);if(er.error||dr.error||mr.error){searchRows=[];if(status)status.textContent='讀取失敗，請稍後再試。';return}const deckMap=new Map((dr.data||[]).map(d=>[String(d.id),d])),matchMap=new Map();for(const m of mr.data||[]){const k=String(m.event_id);if(!matchMap.has(k))matchMap.set(k,{names:[],pokemon:[]});const g=matchMap.get(k);if(m.opponent_deck_name&&!g.names.includes(m.opponent_deck_name))g.names.push(m.opponent_deck_name);if(m.opponent_pokemon_name&&!g.pokemon.includes(m.opponent_pokemon_name))g.pokemon.push(m.opponent_pokemon_name)}searchRows=(er.data||[]).map(e=>{const d=e.own_deck_id?deckMap.get(String(e.own_deck_id)):null,g=matchMap.get(String(e.id))||{names:[],pokemon:[]};return{id:e.id,date:e.event_date||'',location:e.location||'',league:e.league_type||'',format:e.match_format||'',participants:+e.participants||0,placement:+e.placement||0,lp:+e.lp||0,ownDeck:d?.name||'',ownPokemon:[d?.primary_pokemon_name,d?.secondary_pokemon_name].filter(Boolean).join(' '),opponents:g.names,opponentPokemon:g.pokemon}});loadedUser=uid;renderSearch()}
function searchText(r){return norm([r.date,r.date?.replaceAll('-','/'),r.location,LEAGUE[r.league]||'',r.format,r.ownDeck,r.ownPokemon,r.opponents.join(' '),r.opponentPokemon.join(' '),r.participants,r.placement,r.lp].join(' '))}
function renderSearch(){const input=document.getElementById('searchInputV57'),box=document.getElementById('searchResultsV57'),status=document.getElementById('searchStatusV57');if(!box||!status)return;const q=norm(input?.value||''),tokens=q?q.split(' ').filter(Boolean):[];let rows=searchRows.filter(r=>activeLeague==='all'||r.league===activeLeague);if(tokens.length)rows=rows.filter(r=>{const t=searchText(r);return tokens.every(x=>t.includes(x))});rows=[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,80);status.textContent=tokens.length||activeLeague!=='all'?'找到 '+rows.length+' 場':'最近 '+Math.min(rows.length,80)+' 場比賽';if(!rows.length){box.innerHTML='<div class="v57-empty">找不到符合的比賽紀錄。</div>';return}box.innerHTML=rows.map(r=>{const own=r.ownDeck?'｜'+r.ownDeck:'',opp=r.opponents.length?'｜對手：'+r.opponents.slice(0,3).join('、'):'';return '<button type="button" class="v57-search-result" data-v57-event="'+esc(r.id)+'"><span><strong>'+esc(r.location||'未命名比賽')+'</strong><small>'+esc((r.date||'').replaceAll('-','/'))+'｜第 '+r.placement+' 名'+esc(own+opp)+'</small></span><span class="v57-search-result-meta"><b>'+esc(LEAGUE[r.league]||r.league||'')+'</b>'+r.lp+' LP</span></button>'}).join('')}
async function jumpToRecord(r){await switchPage('home');const find=()=>{const date=(r.date||'').replaceAll('-','/');const card=[...document.querySelectorAll('.event-card')].find(c=>(c.querySelector('.date')?.textContent.trim()||'')===date&&(c.querySelector('.loc')?.textContent.trim()||'')===r.location&&(c.querySelector('.meta')?.textContent||'').includes('第 '+r.placement+' 名'));if(!card)return false;card.scrollIntoView({behavior:'smooth',block:'center'});card.classList.remove('v57-record-highlight');void card.offsetWidth;card.classList.add('v57-record-highlight');setTimeout(()=>card.classList.remove('v57-record-highlight'),1900);return true};requestAnimationFrame(()=>{if(!find())setTimeout(find,120)})}
function bindAccount(root){root.querySelector('.v57-login').addEventListener('click',()=>document.getElementById('login')?.click());root.querySelector('.v57-logout').addEventListener('click',()=>document.getElementById('logout')?.click());const auth=document.querySelector('.auth');if(auth)new MutationObserver(()=>{refreshAccount();loadedUser=''}).observe(auth,{childList:true,subtree:true,attributes:true})}
function refreshAccount(){const p=document.querySelector('.v57-page-account');if(!p)return;const state=document.getElementById('authState')?.textContent||'本機模式',email=document.getElementById('authEmail')?.textContent||'',sync=document.getElementById('syncState')?.textContent||'',logged=document.getElementById('login')?.hidden===true;p.querySelector('.v57-account-state').textContent=state;p.querySelector('.v57-account-email').textContent=email;p.querySelector('.v57-account-sync').textContent=sync;p.querySelector('.v57-login').hidden=logged;p.querySelector('.v57-logout').hidden=!logged}
function init(){document.querySelectorAll('dialog.v56-sheet').forEach(d=>{try{if(d.open)d.close()}catch{}});ensurePages();const ver=document.querySelector('.app-version-v14');if(ver)new MutationObserver(stampVersion).observe(ver,{childList:true,characterData:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80));else setTimeout(init,80);
})();
