(()=>{'use strict';
window.__pokemonMobileNavV56=true;
window.__pokemonAppPagesV57=true;
window.__pokemonV571Fix=true;
if(window.__pokemonAppPagesV572)return;window.__pokemonAppPagesV572=true;
const SUPABASE_URL='https://ceobnyikrudlxasyjukg.supabase.co',SUPABASE_KEY='sb_publishable_6uVBALI1T3lMZoFEUiLK4g__R7gv0fz';
const LEAGUE={all:'全部',great:'超級球',premier:'紀念球',ultra:'高級球',master:'大師球',world:'世界賽'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').toLocaleLowerCase('zh-Hant').replace(/\s+/g,' ').trim();
const ICONS={home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5"/><path d="M9.5 21v-6h5v6"/></svg>',search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>',add:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',analysis:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',account:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a4.2 4.2 0 1 0 0-8.4 4.2 4.2 0 0 0 0 8.4Zm0 2c-4.7 0-8 2.4-8 5.1 0 .7.6 1.3 1.3 1.3h13.4c.7 0 1.3-.6 1.3-1.3C20 16.4 16.7 14 12 14Z"/></svg>'};
let db=null,searchRows=[],activeLeague='all',searchTimer=null;
function getDb(){if(!db&&window.supabase)db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return db}
function stampVersion(){const v=document.querySelector('.app-version-v14');if(v){v.textContent='V5.7.2';v.title='目前版本 V5.7.2'}}
function navBtn(key,label,add=false){return '<button type="button" class="v572-nav-btn '+(key==='home'?'is-active ':'')+(add?'v572-add':'')+'" data-v572-nav="'+key+'">'+(add?'<span class="v572-add-circle">'+ICONS.add+'</span>':ICONS[key])+'<span>'+label+'</span></button>'}
function navMarkup(cls){return '<nav class="'+cls+'" aria-label="主要導覽">'+navBtn('home','首頁')+navBtn('search','搜尋')+navBtn('add','新增',true)+navBtn('analysis','分析')+navBtn('account','我的')+'</nav>'}
function cleanupOld(){
  const app=document.querySelector('.app'),bottom=document.querySelector('section.panel.bottom');
  if(app&&bottom&&!app.contains(bottom.parentElement?.closest?.('.v572-page-account'))&&bottom.closest('.v57-page-account'))app.appendChild(bottom);
  document.querySelectorAll('.mobile-bottom-nav-v56,dialog.v56-sheet,.v57-mobile-nav,.v57-desktop-nav,.v57-page').forEach(n=>{if(bottom&&n.contains(bottom)&&app)app.appendChild(bottom);n.remove()});
  document.body.classList.remove('v57-ready','v56-mobile-ready');delete document.body.dataset.v57Page;
}
function ensurePages(){
  cleanupOld();
  const app=document.querySelector('.app'),summary=document.querySelector('.summary'),list=document.getElementById('list'),homePanel=list?.closest('section.panel'),bottom=document.querySelector('section.panel.bottom');if(!app||!summary||!homePanel)return;
  homePanel.classList.add('v572-home-panel');
  const listhead=homePanel.querySelector('.listhead');if(listhead&&!listhead.querySelector('.v572-home-count')){const count=document.createElement('span');count.className='v572-home-count';count.textContent=(document.getElementById('count')?.textContent||'0')+' 場';listhead.querySelector('div')?.appendChild(count);const c=document.getElementById('count');if(c)new MutationObserver(()=>count.textContent=(c.textContent||'0')+' 場').observe(c,{childList:true,characterData:true,subtree:true})}
  const filter=document.getElementById('filter');if(filter&&filter.value!=='all'){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}))}
  if(!document.querySelector('.v572-desktop-nav'))document.querySelector('header')?.insertAdjacentHTML('afterend',navMarkup('v572-desktop-nav'));
  if(!document.querySelector('.v572-mobile-nav'))document.body.insertAdjacentHTML('beforeend',navMarkup('v572-mobile-nav'));
  const search=document.createElement('section');search.className='v572-page v572-page-search v572-page-shell';search.innerHTML='<div class="v572-page-head"><h2>搜尋比賽紀錄</h2><p>搜尋地點、自己的牌組、對手牌組或寶可夢；賽事篩選也集中在這裡。</p></div><div class="v572-search-help">名次標示依最終名次顯示冠軍／亞軍／TOP 4／TOP 8／TOP 16。LP 總分仍取可計分賽事最高 8 場。</div><div class="v572-search-input-wrap"><input id="searchInputV572" class="v572-search-input" type="search" autocomplete="off" placeholder="搜尋比賽、地點、牌組、對手牌組…"><span class="v572-search-icon">'+ICONS.search+'</span></div><div class="v572-search-chips">'+Object.entries(LEAGUE).map(([k,v])=>'<button type="button" class="v572-chip '+(k==='all'?'is-active':'')+'" data-v572-league="'+k+'">'+v+'</button>').join('')+'</div><div id="searchStatusV572" class="v572-search-status"></div><div id="searchResultsV572" class="v572-search-results"></div>';app.appendChild(search);bindSearch(search);
  const analysis=document.createElement('section');analysis.className='v572-page v572-page-analysis v572-page-shell';analysis.innerHTML='<div class="v572-page-head"><h2>分析</h2><p>這裡會作為之後的賽季與牌組分析頁。</p></div><div class="v572-analysis-card"><div class="v572-analysis-icon">'+ICONS.analysis+'</div><h3>分析功能規劃中</h3><p>預計加入年度戰績、自己的牌組使用率與勝率、對手牌組分布，以及勝率／敗率等統計。</p><div class="v572-plan-tags"><span>年度戰績</span><span>牌組使用率</span><span>勝敗率</span><span>對手環境</span></div></div>';app.appendChild(analysis);
  const account=document.createElement('section');account.className='v572-page v572-page-account v572-page-shell';account.innerHTML='<div class="v572-page-head"><h2>我的</h2><p>帳號、同步狀態、資料備份與使用說明集中在這裡。</p></div><div class="v572-account-summary"><div class="v572-account-avatar">'+ICONS.account+'</div><div class="v572-account-copy"><div class="v572-account-state"></div><div class="v572-account-email"></div><div class="v572-account-sync"></div></div><div class="v572-account-actions"><button type="button" class="btn primary v572-login">使用 Google 登入</button><button type="button" class="btn v572-logout">登出</button></div></div>';if(bottom)account.appendChild(bottom);app.appendChild(account);bindAccount(account);
  document.body.classList.add('v572-ready');document.body.dataset.v572Page='home';bindNav();refreshAccount();stampVersion();setTimeout(stampVersion,500);
}
function setActive(key){document.querySelectorAll('[data-v572-nav]').forEach(b=>b.classList.toggle('is-active',b.dataset.v572Nav===key))}
function bindNav(){if(document.body.dataset.v572NavBound==='1')return;document.body.dataset.v572NavBound='1';document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-v572-nav]');if(!b)return;const k=b.dataset.v572Nav;if(k==='add'){const q=document.querySelector('.quick-add-v14');if(q)q.click();else{document.getElementById('reset')?.click();const d=document.getElementById('eventDialogV14');try{if(d&&!d.open)d.showModal()}catch{}}return}await switchPage(k)})}
async function switchPage(key){if(!['home','search','analysis','account'].includes(key))key='home';document.body.dataset.v572Page=key;setActive(key);if(key==='home'){const f=document.getElementById('filter');if(f&&f.value!=='all'){f.value='all';f.dispatchEvent(new Event('change',{bubbles:true}))}window.scrollTo({top:0,behavior:'smooth'});return}window.scrollTo({top:0,behavior:'auto'});if(key==='search'){activeLeague='all';document.querySelectorAll('[data-v572-league]').forEach(x=>x.classList.toggle('is-active',x.dataset.v572League==='all'));const i=document.getElementById('searchInputV572');if(i)i.value='';await loadSearch();setTimeout(()=>i?.focus(),70)}if(key==='account')refreshAccount()}
function bindSearch(root){const input=root.querySelector('#searchInputV572');input.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderSearch,80)});root.querySelectorAll('[data-v572-league]').forEach(btn=>btn.addEventListener('click',()=>{activeLeague=btn.dataset.v572League;root.querySelectorAll('[data-v572-league]').forEach(x=>x.classList.toggle('is-active',x===btn));renderSearch()}));root.querySelector('#searchResultsV572').addEventListener('click',e=>{const b=e.target.closest?.('[data-v572-event]');if(!b)return;const r=searchRows.find(x=>String(x.id)===String(b.dataset.v572Event));if(r)jumpToRecord(r)})}
async function loadSearch(){const status=document.getElementById('searchStatusV572'),client=getDb();if(status)status.textContent='讀取比賽紀錄…';if(!client){searchRows=[];if(status)status.textContent='搜尋功能暫時無法載入。';return}const{data:{session}}=await client.auth.getSession();if(!session){let local=[];try{local=JSON.parse(localStorage.getItem('pokemon-lp-events')||'[]')}catch{}searchRows=(Array.isArray(local)?local:[]).map((e,i)=>({id:e.id||'local-'+i,date:e.date||'',location:e.location||'',league:e.league||'',format:e.matchFormat||'',participants:+e.participants||0,placement:+e.placement||0,lp:+e.lp||0,ownDeck:'',ownPokemon:'',opponents:[],opponentPokemon:[]}));renderSearch();return}const uid=session.user.id;const[er,dr,mr]=await Promise.all([client.from('events').select('id,event_date,location,league_type,match_format,participants,placement,lp,own_deck_id').eq('user_id',uid).order('event_date',{ascending:false}),client.from('decks').select('id,name,primary_pokemon_name,secondary_pokemon_name').eq('user_id',uid),client.from('matches').select('event_id,opponent_deck_name,opponent_pokemon_name').eq('user_id',uid)]);if(er.error||dr.error||mr.error){searchRows=[];if(status)status.textContent='讀取失敗，請稍後再試。';return}const deckMap=new Map((dr.data||[]).map(d=>[String(d.id),d])),matchMap=new Map();for(const m of mr.data||[]){const k=String(m.event_id);if(!matchMap.has(k))matchMap.set(k,{names:[],pokemon:[]});const g=matchMap.get(k);if(m.opponent_deck_name&&!g.names.includes(m.opponent_deck_name))g.names.push(m.opponent_deck_name);if(m.opponent_pokemon_name&&!g.pokemon.includes(m.opponent_pokemon_name))g.pokemon.push(m.opponent_pokemon_name)}searchRows=(er.data||[]).map(e=>{const d=e.own_deck_id?deckMap.get(String(e.own_deck_id)):null,g=matchMap.get(String(e.id))||{names:[],pokemon:[]};return{id:e.id,date:e.event_date||'',location:e.location||'',league:e.league_type||'',format:e.match_format||'',participants:+e.participants||0,placement:+e.placement||0,lp:+e.lp||0,ownDeck:d?.name||'',ownPokemon:[d?.primary_pokemon_name,d?.secondary_pokemon_name].filter(Boolean).join(' '),opponents:g.names,opponentPokemon:g.pokemon}});renderSearch()}
function searchText(r){return norm([r.date,r.date?.replaceAll('-','/'),r.location,LEAGUE[r.league]||'',r.format,r.ownDeck,r.ownPokemon,r.opponents.join(' '),r.opponentPokemon.join(' '),r.participants,r.placement,r.lp].join(' '))}
function renderSearch(){const input=document.getElementById('searchInputV572'),box=document.getElementById('searchResultsV572'),status=document.getElementById('searchStatusV572');if(!box||!status)return;const q=norm(input?.value||''),tokens=q?q.split(' ').filter(Boolean):[];let rows=searchRows.filter(r=>activeLeague==='all'||r.league===activeLeague);if(tokens.length)rows=rows.filter(r=>{const t=searchText(r);return tokens.every(x=>t.includes(x))});rows=[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,80);status.textContent=tokens.length||activeLeague!=='all'?'找到 '+rows.length+' 場':'最近 '+Math.min(rows.length,80)+' 場比賽';if(!rows.length){box.innerHTML='<div class="v572-empty">找不到符合的比賽紀錄。</div>';return}box.innerHTML=rows.map(r=>{const own=r.ownDeck?'｜'+r.ownDeck:'',opp=r.opponents.length?'｜對手：'+r.opponents.slice(0,3).join('、'):'';return '<button type="button" class="v572-search-result" data-v572-event="'+esc(r.id)+'"><span><strong>'+esc(r.location||'未命名比賽')+'</strong><small>'+esc((r.date||'').replaceAll('-','/'))+'｜第 '+r.placement+' 名'+esc(own+opp)+'</small></span><span class="v572-search-result-meta"><b>'+esc(LEAGUE[r.league]||r.league||'')+'</b>'+r.lp+' LP</span></button>'}).join('')}
async function jumpToRecord(r){await switchPage('home');const find=()=>{const date=(r.date||'').replaceAll('-','/');const card=[...document.querySelectorAll('.event-card')].find(c=>(c.querySelector('.date')?.textContent.trim()||'')===date&&(c.querySelector('.loc')?.textContent.trim()||'')===r.location&&(c.querySelector('.meta')?.textContent||'').includes('第 '+r.placement+' 名'));if(!card)return false;card.scrollIntoView({behavior:'smooth',block:'center'});card.classList.remove('v572-record-highlight');void card.offsetWidth;card.classList.add('v572-record-highlight');setTimeout(()=>card.classList.remove('v572-record-highlight'),1800);return true};requestAnimationFrame(()=>{if(!find())setTimeout(find,120)})}
function bindAccount(root){root.querySelector('.v572-login').addEventListener('click',()=>document.getElementById('login')?.click());root.querySelector('.v572-logout').addEventListener('click',()=>document.getElementById('logout')?.click());const auth=document.querySelector('.auth');if(auth)new MutationObserver(refreshAccount).observe(auth,{childList:true,subtree:true,attributes:true})}
function refreshAccount(){const p=document.querySelector('.v572-page-account');if(!p)return;const state=document.getElementById('authState')?.textContent||'本機模式',email=document.getElementById('authEmail')?.textContent||'',sync=document.getElementById('syncState')?.textContent||'',logged=document.getElementById('login')?.hidden===true;p.querySelector('.v572-account-state').textContent=state;p.querySelector('.v572-account-email').textContent=email;p.querySelector('.v572-account-sync').textContent=sync;p.querySelector('.v572-login').hidden=logged;p.querySelector('.v572-logout').hidden=!logged}
async function recoverCloudIfNeeded(){try{if(sessionStorage.getItem('pokemon-v572-recovered')==='1')return;const client=getDb();if(!client)return;const{data:{session}}=await client.auth.getSession();if(!session)return;const shown=Number(document.getElementById('count')?.textContent||0);if(shown>0)return;const{count,error}=await client.from('events').select('id',{count:'exact',head:true}).eq('user_id',session.user.id);if(error||!count||count<1)return;sessionStorage.setItem('pokemon-v572-recovered','1');if('caches'in window){for(const k of await caches.keys())if(k.startsWith('pokemon-lp-tracker-'))await caches.delete(k)}location.replace(location.pathname+'?v=5.7.2')}catch{}}
function init(){ensurePages();stampVersion();setTimeout(recoverCloudIfNeeded,1400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,100));else setTimeout(init,100);
})();